name:                vending-machine
version:             0.1.0.0
github:              "nkarag/haskell-vending-machine"
license:             BSD3
author:              "Nikos Karagiannidis"
maintainer:          "nkarag@gmail.com"
copyright:           "2019 Nikos Karagiannidis"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nkarag/haskell-vending-machine#readme>

dependencies:
- base >= 4.7 && < 5
- small-steps

library:
  source-dirs: src

executables:
  vending-machine-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vending-machine

tests:
  vending-machine-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vending-machine
    - tasty
    - tasty-hunit
    - tasty-hedgehog
    - transformers
